### ISSUE TITLE
problem when trying to select sprites

### ISSUE THREAD

**Issue by drcucaracha** [nonunknown/godot-sheet-manager#1]
hello I wanted to test the complement but when loading a sheet sprites and pressing f9 I cannot select the probe sprites with a sheet that I download from the internet and also test cracking them from the web that I leave but without success

**Comment by nonunknown** [comment]
Before we proceed, answer some basic questions for me plz:

* Did you followed README tutorial on how to use?
* This spritesheet you have in hands was made with: https://www.leshylabs.com/apps/sstool/?

This plugins only works if you have for example X amount of sprites and generate them with the link above, and set to export the json file.

**Workaround**
If you found a already done spritesheet on the internet, you can use a tool called: **shoebox** which can get sprites from the spritesheet and turn it into several images, and then use the like mentioned above to create the spritesheet.

If you dont want to use the link, in case you have texturepacker, you should modify the plugin to support the tpsheet file generated by texturepacker, same with shoebox(which is free)

**Comment by drcucaracha** [comment]
@nonunknown I did it the same as in the readme

<a href="https://ibb.co/4FJSdCR"><img src="https://i.ibb.co/VL3CmbY/01.png" alt="01" border="0" /></a>

<a href="https://ibb.co/SxzGjD5"><img src="https://i.ibb.co/yRr79md/03.png" alt="03" border="0" /></a>

<a href="https://ibb.co/n3x0DC9"><img src="https://i.ibb.co/Xyc4z81/02.png" alt="02" border="0" /></a>

**Comment by nonunknown** [comment]
another question, the json file is in the same folder as the spritesheet? and the json's file name is the same as the spritesheet?

If the answer is yes to both questions, if you make a video of the entire process, showing the output strings should help me track the issue, or sending the project too

**Comment by drcucaracha** [comment]
@nonunknown yes  and yes  , video in gif so I save make an account on youtube

<a href="https://gifyu.com/image/lRF0"><img src="https://s4.gifyu.com/images/VIDEO2.gif" alt="VIDEO2.gif" border="0" /></a>

<a href="https://ibb.co/5RrYcCh"><img src="https://i.ibb.co/P6cTCJG/01.png" alt="01" border="0" /></a>

**Comment by nonunknown** [comment]
From the image above I can tell you, you skipped step 4 from tutorial:

How to use

1 Create your spritesheet here: https://www.leshylabs.com/apps/sstool/
2 Set the FileName type to json
3 JSON and PNG file must be the same name, and located in the same folder
4 Go to your Scene which contains:
        AnimationPlayer
        Sprite **(Attach SpriteSheet2D or SpriteSheet3D scripts)**

You forgot to attach the SpriteSheet script to your sprite node!

**Comment by drcucaracha** [comment]
@nonunknown 
If the problem actually works, it was me who did not know that I had to add the script since I thought they were part of the tool, thank you very much and sorry for having wasted your time for an error as simple as mine

**Comment by nonunknown** [comment]
no problem dude, you're very welcome. Hope to have more feedbacks from you soon, such as improvements ideas,PRs, or even bugs.
